-- ============================================================
-- WorkFlow - Database Tables
-- ============================================================
-- Purpose:
-- Initial database structure for the Oracle APEX portfolio application.
-- ============================================================

CREATE TABLE departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR2(100) NOT NULL,
    description   VARCHAR2(500),

    CONSTRAINT pk_departments
        PRIMARY KEY (department_id),

    CONSTRAINT uk_departments_name
        UNIQUE (name)
);


CREATE TABLE users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_id  NUMBER NOT NULL,
    username       VARCHAR2(100) NOT NULL,
    full_name      VARCHAR2(200) NOT NULL,
    email          VARCHAR2(255) NOT NULL,
    role           VARCHAR2(30) NOT NULL,
    active         CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_users
        PRIMARY KEY (user_id),

    CONSTRAINT fk_users_department
        FOREIGN KEY (department_id)
        REFERENCES departments (department_id),

    CONSTRAINT uk_users_username
        UNIQUE (username),

    CONSTRAINT uk_users_email
        UNIQUE (email),

    CONSTRAINT ck_users_role
        CHECK (role IN ('ADMIN', 'AGENT', 'USER')),

    CONSTRAINT ck_users_active
        CHECK (active IN ('Y', 'N'))
);


CREATE TABLE assets (
    asset_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    asset_tag         VARCHAR2(50) NOT NULL,
    asset_type        VARCHAR2(50) NOT NULL,
    description       VARCHAR2(500),
    status            VARCHAR2(30) NOT NULL,
    assigned_user_id  NUMBER,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_assets
        PRIMARY KEY (asset_id),

    CONSTRAINT fk_assets_user
        FOREIGN KEY (assigned_user_id)
        REFERENCES users (user_id),

    CONSTRAINT uk_assets_tag
        UNIQUE (asset_tag),

    CONSTRAINT ck_assets_status
        CHECK (status IN ('AVAILABLE', 'ASSIGNED', 'MAINTENANCE', 'RETIRED'))
);


CREATE TABLE tickets (
    ticket_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title          VARCHAR2(200) NOT NULL,
    description    CLOB,
    priority       VARCHAR2(20) NOT NULL,
    status         VARCHAR2(30) NOT NULL,
    created_by     NUMBER NOT NULL,
    assigned_to    NUMBER,
    asset_id       NUMBER,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_tickets
        PRIMARY KEY (ticket_id),

    CONSTRAINT fk_tickets_created_by
        FOREIGN KEY (created_by)
        REFERENCES users (user_id),

    CONSTRAINT fk_tickets_assigned_to
        FOREIGN KEY (assigned_to)
        REFERENCES users (user_id),

    CONSTRAINT fk_tickets_asset
        FOREIGN KEY (asset_id)
        REFERENCES assets (asset_id),

    CONSTRAINT ck_tickets_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),

    CONSTRAINT ck_tickets_status
        CHECK (status IN (
            'OPEN',
            'IN_PROGRESS',
            'RESOLVED',
            'CLOSED'
        ))
);


CREATE TABLE ticket_comments (
    comment_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ticket_id     NUMBER NOT NULL,
    user_id       NUMBER NOT NULL,
    comment_text  CLOB NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_ticket_comments
        PRIMARY KEY (comment_id),

    CONSTRAINT fk_comments_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES tickets (ticket_id),

    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
);


CREATE TABLE ticket_history (
    history_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ticket_id   NUMBER NOT NULL,
    changed_by  NUMBER NOT NULL,
    old_status  VARCHAR2(30),
    new_status  VARCHAR2(30) NOT NULL,
    changed_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_ticket_history
        PRIMARY KEY (history_id),

    CONSTRAINT fk_history_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES tickets (ticket_id),

    CONSTRAINT fk_history_user
        FOREIGN KEY (changed_by)
        REFERENCES users (user_id)
);
